
development:
  adapter: postgresql
  database: mezzo_development
  username: postgres
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  database: mezzo_test
  username: postgres
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  adapter: postgresql
  database: mezzo_production
  username: postgres
  pool: 5
  timeout: 5000
  encoding: utf8